#400G
[[proxies]]
name = "smb_share_feiniu"
type = "tcp"
remotePort = 7001
[proxies.plugin]
type = "static_file"
localPath = "/vol00/WDC WD4000FYYZ-01UL1B3"
stripPrefix = ""
httpUser = "test"
httpPassword = "test1234"

# data
[[proxies]]
name = "smb_share_data"
type = "tcp"
remotePort = 7002
[proxies.plugin]
type = "static_file"
localPath = "/vol1/1000"
stripPrefix = ""

#aliyunpan
[[proxies]]
name = "smb_share_aliyunpan"
type = "tcp"
remotePort = 7003
[proxies.plugin]
type = "static_file"
localPath = "/vol02/1000-1-7c388700"
stripPrefix = ""