#400G
[[proxies]]
name = "smb_share_feiniu"
type = "tcp"
remotePort = 7001
[proxies.plugin]
type = "static_file"
# 本地文件目录，对外提供访问
localPath = "/vol00/WDC WD5000LPLX-66ZNTT1"
# URL 中的前缀，将被去除，保留的内容即为要访问的文件路径
stripPrefix = ""
#httpUser = "test"
#httpPassword = "test1234"

#macos-usb
[[proxies]]
name = "smb_share_apk"
type = "tcp"
remotePort = 7002
[proxies.plugin]
type = "static_file"
# 本地文件目录，对外提供访问
localPath = "/vol02/1000-0-df070305"
# URL 中的前缀，将被去除，保留的内容即为要访问的文件路径
stripPrefix = ""

#data1
[[proxies]]
name = "smb_share_data"
type = "tcp"
remotePort = 7003
[proxies.plugin]
type = "static_file"
# 本地文件目录，对外提供访问
localPath = "/vol02/1000-0-d0b39145"
# URL 中的前缀，将被去除，保留的内容即为要访问的文件路径
stripPrefix = ""

#aliyunpan
name = "smb_share_aliyunpan"
type = "tcp"
remotePort = 7004
[proxies.plugin]
type = "static_file"
# 本地文件目录，对外提供访问
localPath = "/vol02/1000-1-bec4dcf0"
# URL 中的前缀，将被去除，保留的内容即为要访问的文件路径
stripPrefix = ""