serverAddr = "hongkong.gpg123.vip"   #"hcs.gpg123.vip"
serverPort = 7000
auth.token = "ADt8zh5VFdJKcccVWh2jkv1l6Z0IblSvm0H7M2yclJpYkWV0KPEadr9gZWdd77HM"  # 与服务端一致
#不能删除, 否则连接不上会闪退
loginFailExit=false

# emby
[[proxies]]
name = "emby"
type = "http"
localIP = "127.0.0.1"
localPort = 8096
customDomains = ["emby.nas.gpg123.vip"]

# video
[[proxies]]
name = "fn-video"
type = "http"
localIP = "127.0.0.1"
localPort = 8005
customDomains = ["video.nas.gpg123.vip","video1.nas.gpg123.vip","video2.nas.gpg123.vip","video3.nas.gpg123.vip","video4.nas.gpg123.vip","video5.nas.gpg123.vip"]

# video
[[proxies]]
name = "jellyfin-video-server"
type = "http"
localIP = "127.0.0.1"
localPort = 8096
customDomains = ["jf-video.nas.gpg123.vip","jf-video1.nas.gpg123.vip","jf-video2.nas.gpg123.vip","jf-video3.nas.gpg123.vip"]

# 相册
[[proxies]]
name = "fn-picture"
type = "http"
localIP = "127.0.0.1"
localPort = 8006
customDomains = ["picture.nas.gpg123.vip","picture1.nas.gpg123.vip","picture2.nas.gpg123.vip","picture3.nas.gpg123.vip"]

#飞牛
[[proxies]]
name = "feiniu-nas"
type = "http"
localIP = "127.0.0.1"
localPort = 5666
customDomains = ["nas.gpg123.vip"]

#400G
[[proxies]]
name = "smb_share_feiniu"
type = "tcp"
remotePort = 7001
[proxies.plugin]
type = "static_file"
# 本地文件目录，对外提供访问
localPath = "/vol00/WDC WD5000LPLX-66ZNTT1"
# URL 中的前缀，将被去除，保留的内容即为要访问的文件路径
stripPrefix = ""
#httpUser = "test"
#httpPassword = "test1234"

#macos-usb
[[proxies]]
name = "smb_share_apk"
type = "tcp"
remotePort = 7002
[proxies.plugin]
type = "static_file"
# 本地文件目录，对外提供访问
localPath = "/vol02/1000-0-df070305"
# URL 中的前缀，将被去除，保留的内容即为要访问的文件路径
stripPrefix = ""

#data1
[[proxies]]
name = "smb_share_data"
type = "tcp"
remotePort = 7003
[proxies.plugin]
type = "static_file"
# 本地文件目录，对外提供访问
localPath = "/vol02/1000-0-d0b39145"
# URL 中的前缀，将被去除，保留的内容即为要访问的文件路径
stripPrefix = ""