serverAddr = "hongkong.gpg123.vip"   #"hcs.gpg123.vip"
serverPort = 7000
#includes = ["./confd/*.toml"]
auth.token = "ADt8zh5VFdJKcccVWh2jkv1l6Z0IblSvm0H7M2yclJpYkWV0KPEadr9gZWdd77HM"  # 与服务端一致
#不能删除, 否则连接不上会闪退
loginFailExit=false

#prometheus
[[proxies]]
name = "prometheus"
type = "http"
localIP = "127.0.0.1"
localPort = 9090
customDomains = ["prometheus.nas.gpg123.vip"]

#prometheus-alert
[[proxies]]
name = "prometheus-alert"
type = "http"
localIP = "127.0.0.1"
localPort = 9093
customDomains = ["prometheus-alert.nas.gpg123.vip","alert.nas.gpg123.vip"]

#node-exporter
[[proxies]]
name = "node-exporter"
type = "http"
localIP = "127.0.0.1"
localPort = 9100
customDomains = ["node-exporter.nas.gpg123.vip"]

#amd-smi-exporter
[[proxies]]
name = "amd-smi-exporter"
type = "http"
localIP = "127.0.0.1"
localPort = 2021
customDomains = ["amd-smi-exporter.nas.gpg123.vip"]

#amd-gpu-exporter
[[proxies]]
name = "amd-gpu-exporter"
type = "http"
localIP = "127.0.0.1"
localPort = 5000
customDomains = ["amd-gpu-exporter.nas.gpg123.vip"]

#转发ollam-api
[[proxies]]
name = "ollama-api"
type = "tcp"
localIP = "127.0.0.1"
localPort = 11434
remotePort = 11434

#转发 Unix 域套接字
[[proxies]]
name = "unix_docker_socket"
type = "tcp"
remotePort = 2345
[proxies.plugin]
type = "unix_domain_socket"
# Unix 域套接字路径
unixPath = "/var/run/docker.sock"

#转发 Unix 域套接字
[[proxies]]
name = "unix_containerd_socket"
type = "tcp"
remotePort = 10100
[proxies.plugin]
type = "unix_domain_socket"
# Unix 域套接字路径
unixPath = "/var/run/containerd.sock"

#ssh
[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 122