serverAddr = "145.79.143.28"
serverPort = 7000
# token
auth.token = "ADt8zh5VFdJKcccVWh2jkv1l6Z0IblSvm0H7M2yclJpYkWV0KPEadr9gZWdd77HM"
#不能删除, 否则连接不上会闪退
loginFailExit=false
# 分片
includes = ["/home/nas/frp/client_config/*.toml"]
