serverAddr = "hongkong.gpg123.vip"
serverPort = 7000
auth.token = "ADt8zh5VFdJKcccVWh2jkv1l6Z0IblSvm0H7M2yclJpYkWV0KPEadr9gZWdd77HM"  # 与服务端一致
#client-admin-ui
webServer.addr = "127.0.0.1"
webServer.port = 7500
webServer.user = "gaopuguang"
webServer.password = "1999y4m30d"
# emby
[[proxies]]
name = "emby"
type = "http"
localIP = "127.0.0.1"
localPort = 8096
customDomains = ["emby.nas.gpg123.vip"]  # 需解析到服务器IP[5,7](@ref)
# video
[[proxies]]
name = "video"
type = "http"
localIP = "127.0.0.1"
localPort = 8005
customDomains = ["video.nas.gpg123.vip"]  # 需解析到服务器IP[5,7](@ref)
# 相册
[[proxies]]
name = "picture"
type = "http"
localIP = "127.0.0.1"
localPort = 8006
customDomains = ["picture.nas.gpg123.vip"]
#飞牛
[[proxies]]
name = "feiniu-nas"
type = "http"
localIP = "127.0.0.1"
localPort = 5666
customDomains = ["nas.gpg123.vip"]

# 示例2：SSH穿透（TCP模式）
#[[proxies]]
#name = "ssh"
#type = "tcp"
#localIP = "127.0.0.1"
#localPort = 22
#remotePort = 2222  # 公网访问端口[2,4](@ref)

# HTTPS反向代理（需SSL证书）
#[[proxies]]
#name = "https_proxy"
#type = "https"
#customDomains = ["ssl.domain.com"]
#[[proxies.plugin]]
#type = "https2http"
#localAddr = "192.168.1.100:80"
#crtPath = "/path/to/cert.crt"
#keyPath = "/path/to/cert.key"  # 证书路径需真实存在[5](@ref)

# Enable HTTP health check
healthCheck.type = "http"
# frpc will send a GET request to '/status'
# and expect an HTTP 2xx OK response
healthCheck.path = "/status"
healthCheck.timeoutSeconds = 3
healthCheck.maxFailed = 3
healthCheck.intervalSeconds = 10