bindPort = 7000
auth.method = "token"
auth.token = "ADt8zh5VFdJKcccVWh2jkv1l6Z0IblSvm0H7M2yclJpYkWV0KPEadr9gZWdd77HM"  # 必填，客户端需一致[4,8](@ref)

# 仪表盘配置（管理界面）
webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "gaopuguang"
webServer.password = "1999y4m30d"  # 避免默认密码[1,8](@ref)

# 域名代理支持（HTTPS需配置）
vhostHTTPPort = 80
#vhostHTTPSPort = 443  # 需配合SSL证书使用[5](@ref)

#开启监控
enablePrometheus = true
